# initially for crontab, maybe others, idk
VISUAL="code --wait"
EDITOR="code --wait"

# ghostty tilde thing
GTK_IM_MODULE=simple

# username for omp theme
HIDE_USERNAME=1

# forcing electron to behave
ELECTRON_OZONE_PLATFORM_HINT=wayland

# paths
HOME_BIN="${HOME}/.local/bin"
USR_LOCAL_BIN=/usr/local/bin
GOPATH="${HOME}/.go"

# PATH
PATH="${HOME_BIN}:${USR_LOCAL_BIN}:${GOPATH}/bin:${PATH}"
