name: local-docker

services:
  postgres:
    container_name: local-postgres
    image: postgres:alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    # - postgres-data:/var/lib/postgresql/data if lower than v18

  mysql:
    container_name: local-mysql
    image: mysql@sha256:66aec17cd21a956029b83f083b813073859e8355dc1a00e55df6ba02f0e32345
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    container_name: local-mongodb
    image: bitnami/mongodb@sha256:1b97815032d03904c324dea54e61c990a8ba3e6ae8d1074b525b6ea1d228f68a
    ports:
      - 27017:27017
    environment:
      MONGODB_ADVERTISED_HOSTNAME: "127.0.0.1"
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - mongodb-data:/bitnami/mongodb
  # connection string must be
  # mongodb://root:root@localhost:27017/database_name?authSource=admin&directConnection=true

  mssql:
    container_name: local-mssql
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:4bab24f36c1ecd48e85f7d37df26e6bf301641d84c3fe652f9a0dcc947d512e1
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: StR0NgP@SsW0Rd
    volumes:
      - mssql-data:/var/opt/mssql

  redis:
    container_name: local-redis
    image: redis:alpine@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576
    command: >
      --requirepass ""
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  dynamodb:
    container_name: local-dynamodb
    image: amazon/dynamodb-local@sha256:ff89bd48ff32cd8d9be5fee8873b65b8854dc408f1afe881be6eb00247bc0dab
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /dynamodb-data"
    ports:
      - 8000:8000
    volumes:
      - dynamodb-data:/dynamodb-data

  rabbitmq:
    container_name: local-rabbitmq
    image: rabbitmq:management-alpine@sha256:e2f08f846de10bb09649a8b020f286ed362a8f72ee45e5a8d043851f1533fda8
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres-data:
  mysql-data:
  mongodb-data:
  mongodb-config-data:
  mssql-data:
  redis-data:
  dynamodb-data:
  rabbitmq-data:
