[commit-msg.commands]
cog-lint = { run = "cog verify --file {1}" }

[pre-commit.commands]
lint = { run = "mise run lint" }

[pre-push.commands]
lint = { run = "mise run lint" }
format = { run = "mise run format-check" }

[post-checkout.commands]
sync-branch = { run = "mise run sync-branch" }

[post-merge.commands]
sync-branch = { run = "mise run sync-branch" }
