package verify //nolint:testpackage // Tests exercise unexported filesystem verification helpers.

import (
	"errors"
	"os"
	"path/filepath"
	"testing"
)

func TestVerifyMirrorlistFilesystem(t *testing.T) {
	const marker = "reflector --country Brazil --latest 20"

	for _, tc := range []struct {
		name    string
		content string
		missing bool
		want    string
	}{
		{name: "marker present", content: "# Generated by " + marker + "\nServer = https://example.invalid/$repo\n"},
		{
			name: "marker absent", content: "# generated by another command\n",
			want: "mirrorlist was not generated with the expected Reflector command",
		},
		{name: "empty file", want: "mirrorlist was not generated with the expected Reflector command"},
		{name: "missing file", missing: true, want: "read mirrorlist"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "mirrorlist with spaces")
			if !tc.missing {
				if err := os.WriteFile(path, []byte(tc.content), 0o600); err != nil {
					t.Fatal(err)
				}
			}

			err := verifyMirrorlist(path, marker)
			if tc.want == "" {
				if err != nil {
					t.Fatal(err)
				}

				return
			}

			filesystemVerifyError(t, err, tc.want)

			if tc.missing && !errors.Is(err, os.ErrNotExist) {
				t.Errorf("expected wrapped ErrNotExist, got %v", err)
			}
		})
	}
}
