monitor.alsa.rules = [
  {
    matches = [
      {
        object.path = "alsa:acp:sofhdadsp:0:playback"
      }
      {
        object.path = "alsa:acp:sofhdadsp:1:playback"
      }
      {
        object.path = "alsa:acp:sofhdadsp:2:playback"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
